### ISSUE TITLE
Presenter screen

### ISSUE THREAD

**Issue by subhojit777** [subhojit777/questionnaire-frontend#2]
**Tasks:**

- [x] Presenter should see the first question of his presentation
- [x] Presenter should see the answers of that question as a bar chart
- [x] Presentation should see option to navigate to previous and next question
