### ISSUE TITLE
Sync presenter and participant screen

### ISSUE THREAD

**Issue by subhojit777** [subhojit777/questionnaire-frontend#3]
**Dependencies:**

- #1 
- #2 

**Tasks:**

- [x] Participant should see the same question that the presenter is presenting
- [x] Participant's screen should be updated automatically when presenter has clicked the navigation buttons
- [ ] When participant has answered a question, the chart in presenter's screen should be updated automatically.

Note: Use web sockets for the implementation. Refer - https://blog.bitlabstudio.com/a-simple-chat-app-with-react-node-and-websocket-35d3c9835807
